### ISSUE TITLE
access-om2 losing too much salt

### ISSUE THREAD

**Issue by nicjhan** [OceansAus/access-om2#16]
This may or may not be related to https://github.com/OceansAus/access-om2/issues/13 which has been resolved. 

@AndyHoggANU has created plots that demonstrate that the model is losing salt. See "Globally Averaged Salinity" here:

https://github.com/OceansAus/cosima-cookbook/blob/master/notebooks/ACCESS-OM2-025%20Preliminary%20Analysis.ipynb

It would be useful to know whether this also occurs in the current ACCESS-OM2 1 deg config. Also in the runs completed by Fabio.

**Comment by nicjhan** [comment]
Fabio's 1deg core2 run looks OK. See attached plots. This narrow's things down a lot. 

![unnamed](https://user-images.githubusercontent.com/921706/28599475-343f8090-71ee-11e7-827f-be672e9cf048.png)

**Comment by russfiedler** [comment]
Looks like it is a water problem. The mean eta_t after 50yr is over 1m

 Area average surface height on tracer cells (tau) =  1.08393849513630203E+00 m

In ferret I fired up a session in /g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf

   let files=spawn("ls -1 */ocean/ocean_scalar.nc")
   tseries scal = files
   can axis/mod time
   plot eta_global
   plot total_ocean_pme_river[l=`@`sbx:12]
   plot total_ocean_salt[l=`@`sbx:12]  ! might be some salt loss but may be due to old bug.

**Comment by russfiedler** [comment]
@nicjhan  @AndyHoggANU I think we need a fresh run with all the latest bug fixes. I saw that there was a recent fix for the JRA55 runoff in MATM. I don't think that's the problem but It's best to remove any confounding variables.
Just had an idea. Yep, total_ocean_pme_river = total_ocean_melt (as expected due to the zeroing) and is always positive over a year (2.5E8 kg/s), which isn't expected. Integrating that over the time interval and dividing by the surface area gives about 1.1 metres of sea level rise. It looks like water is being pumped into the ocean from the ice model.

**Comment by AndyHoggANU** [comment]
Hi @russfiedler @nicjhan 
I agree we need a fresh run. I am going to kick of both 1° and 0.25° as soon as I can. 
With any luck it will run on the weekend and we can reconvene on Monday morning with some new results.

**Comment by nicjhan** [comment]
Hi @russfiedler, thanks for looking at this. 

Just a note,  this run we are looking at is unique in that includes the melt fix but not the salt flux sign fix . See:

- https://github.com/mom-ocean/MOM5/pull/176/files
- https://github.com/mom-ocean/MOM5/commit/f2a120dd67663c7c35e983ffad8e6c0f58af216f

The ACCESS-OM2 runs prior to these two fixes did something interesting: they added (direct) melt to pme but then subtracted a (sign reversed salt flux) melt from pme_river. See:

- https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_sbc.F90#L3214
- https://github.com/mom-ocean/MOM5/blob/master/src/mom5/ocean_core/ocean_sbc.F90#L3535

The above means that melt was added to pme and then added again to pme_river (not subtracted). Later in the code pme = pme - pme_river.

For this reason it would not be surprising that old runs (e.g. Fabio's) would have a smaller PME coming out of get_ocean_sbc() than the new ones.

**Comment by nicjhan** [comment]
@AndyHoggANU I'm wondering whether it would useful to include the spatial water balance variables in one of your runs.

**Comment by russfiedler** [comment]
Hi @nicjhan  @AndyHoggANU  No, it definitely doesn't have the cp_ocean fix. Check the mismatch in the heat flux from the ASCII logs.

/g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf/output050/access-om2.out
...
 Mismatch converted to a surface flux               =  8.26570149254472763E-05 W/m^2

This is what we saw in Fabio's runs. It should be about 6 orders of magnitude smaller.

I think Andy's source is here

/short/v45/amh157/access-om2/src/mom/src/mom5/ocean_access/auscom_ice.F90

That's the old code.

**Comment by nicjhan** [comment]
You're right, it doesn't include the heat budget fix. But it does have a change to the way melt() and pme() is calculated. https://github.com/mom-ocean/MOM5/pull/176/files

**Comment by nicjhan** [comment]
Backing up what @russfiedler has said above. Below are time series plots of ice melt. ACCESS-OM2 is on top, MOM+SIS below. ACCESS-OM2 is not centred around 0, and has a lot of positive melt. This is coming straight from CICE/coupler. 

<img width="970" alt="screen shot 2017-07-28 at 3 55 04 pm" src="https://user-images.githubusercontent.com/921706/28704437-e06561d0-73ad-11e7-8414-78f807b1b44f.png">

**Comment by nicjhan** [comment]
This may be a total or partial fix:

https://github.com/mom-ocean/MOM5/issues/187

**Comment by nicjhan** [comment]
The melt is looking somewhat more balanced now in Andy's 1 deg run. This is a time series of "total_ocean_melt" from ocean_scalar.nc . However we still don't know if we're losing too much salt.

<img width="1044" alt="screen shot 2017-08-07 at 10 56 58 am" src="https://user-images.githubusercontent.com/921706/29008740-499fade6-7b5f-11e7-85a1-85f1bce375c0.png">

**Comment by russfiedler** [comment]
@nicjhan I don't think things are working at all. The surface height has risen by about 0.5m over the century and this is entirely due to the melt which should zero out over the year. There is also a positive net salt flux imbalance which matches this. Run a 12 month box smoother over the results and you'll see what I mean.

**Comment by StephenGriffies** [comment]
I wonder if the drift is due to surface salinity restoring and/or the surface water flux.  Are we normalizing the surface salt flux and surface water flux to zero?  

With surface salinity restoring, there is no guarantee that the net salt entering the ocean will be zero.  Likewise, there is no a priori reason E-P+R should integrate to zero globally.  

There are options in ocean_core/ocean_sbc.F90 meant to address these issues. They amount to performing a global normalization each time step.  This approach is not satisfying in principle, as global normalization means non-local regions are impacted instantaneously.  Nonetheless, this approach is simple and it does remove global drifts.  So it is commonly used for CORE simulation (e.g., GFDL, many others).  Also, I have found the global normalization is not a bottleneck to the simulation (only a 2d global sum needed), though that likely is computer dependent.  

I believe the relevant nml parameters have been inherited from GFDL. So I may be barking up the wrong tree. But it is worth another check.  For that purpose, could someone please post here the fms.out printout for the ocean_sbc setup.  

For the record, here are the ocean_sbc.F90 defaults of relevance to this issue

logical :: salt_restore_under_ice         =.true.
logical :: salt_restore_as_salt_flux      =.true.
logical :: zero_net_salt_restore           =.false.
logical :: zero_net_water_restore        =.false.

I suggest we should be running with 
zero_net_salt_restore           =.true.
zero_net_water_restore        =.true.

to remove the global mean drift.

**Comment by russfiedler** [comment]
@StephenGriffies  I had the same feeling but those options are set. I'll have some other thoughts in an hour or so.

**Comment by russfiedler** [comment]
@nicjhan  @StephenGriffies  @AndyHoggANU   Ok, my hunch was right. The salt content of ice is different in the two components. In CICE5 we have

 ice_ref_salinity = 5._dbl_kind ,&! (ppt) <== mom4 ice_salt_concentration constant

but in MOM

 ICE_SALT_CONCENTRATION  =  4.000000000000000E-003,

These MUST be the same. In the vanilla version of CICE ice_ref_salinity = 4e-3. It's a pain that it has to be set at compile time but so be it. You've got to be careful that things agree across components. It seems to me that some sort of tool needs to be developed to sanity check these things.

The 0.25 model has ice_salt_concentration=5e-3 so it won't have this problem I guess.

**Comment by StephenGriffies** [comment]
Having the salt concentrations differ between ice and ocean will indeed create problems with salt conservation. Good catch! 

For clarity, I wish to be sure I understand the issue.  

CICE "vanilla"  has salt_concentration = 0.004
CICE5 has 0.005 

MOM has a nml in ocean_core/ocean_sbc.F90, "ice_salt_concentration", which is defaulted to 
real    :: ice_salt_concentration         = 0.005  ! kg/kg

This parameter was set via nml to 0.004 to accommodate CICE-vanilla.  However, when updating to CICE5 we needed to change the MOM setting to 0.005.  That change was not done.  The solution is to change the MOM5 nml to 0.005 to match CICE5.  

Is this the proper accounting of the issue?

**Comment by nicjhan** [comment]
Thanks once again @russfiedler, well done. 

@StephenGriffies, I think what has happened here is that we discovered this mismatch a couple of years ago when developing 0.25 degree ACCESS-OM/CM . Unfortunately no one was using the 1 deg and the fix wasn't applied. Your solution sounds good. 

It looks like both CICE4 and CICE5 has used both values at different times. 

After being tripped up by this twice it's definitely time to put some tests in place as suggested by @russfiedler . Not that we need it - but another example of where time spent developing tests saves time in the long run. I've created and issue here https://github.com/OceansAus/access-om2/issues/22

**Comment by ofa001** [comment]
The setting on the salinities has been switched multiple time but it does have to be done by hand every time it does depend on where you got the code from, so I have changed it several times but I don't always for every new version.  The coupled version here has been well checked and well used. The OM is not used by the main group here and that looks like where you have sourced this from Nic. When we switched the CICE5.1 code I am not sure it was checked as carefully as we were more checking more for blow model ups, I did make some suggestions that weren't followed up at the time Dave was overseas, this is coming back to haunt us at the moment.  Russ' idea from a couple of weeks ago of a common namelist across the models is not a bad idea that's picked up at runtime. 
 As has been mentioned before we have a different version of the CICE code (from the UM repository) in the coupled model and we plan to update it again soon and we have add in our local bits by hand.

**Comment by StephenGriffies** [comment]
As a follow up to this thread, I note that the "melt" array in ocean_sbc.F90 is used purely for diagnostics.  It is diagnosed from the salt flux and the ice_concentration parameter.  Details are commented on within the code.  

The melt diagnostic was introduced to MOM5 since the ice model merges melt+precip into a single array in the ice-ocean boundary type.  This merger is inconvenient for many needs of CORE simulations. I thus introduced the melt diagnostic so that I could make use of it. However, again, it does not impact on the prognostic simulation.  

So there must be something different happening in the ACCESS simulations, as the melt array seems to be part of the problem.  Is the melt array in fact sent across to MOM from CICE?

**Comment by russfiedler** [comment]
Steve, there's two extra fields which are passed in ACCESS which represent the fresh water flux where ice is present. These are both misleadingly named: wfiform and wfimelt. They both include rain/evap as well as water from ice formation and melt. These aren't included in lprec in the ACCESS-OM2 case.

The the global integral of the variable "melt" is actually used when setting zero_net_water_coupler=.true. It's the mismatch in the assumed salt concentration between CICE and MOM that produces spurious water and salt fluxes between the components.

**Comment by ofa001** [comment]
Russ, Steve,

Dave implemented the wfimelt and wfiform fields as they better capture the processes going on in the coupling between CICE and MOM we did this after the cmip5 runs were done so that we could better close the water budgets.

We do not include these terms within lprec like you do when passed from SIS.

Siobhan

**Comment by nicjhan** [comment]
I believe that https://github.com/OceansAus/access-om2/issues/18 has made a significant improvement to this problem. Once we have confirmation of this from @AndyHoggANU I think I'll be ready to summarise the issue and close.

**Comment by aekiss** [comment]
Great work! A test of this at 1/4 degree is underway (/g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf_spinup7/ , using matm_jra55_0609e5ad.exe,  fms_ACCESS-OM_030fb1f2.x, cice_auscom_1440x1080_480p_fe730022.exe). 8 years completed so far and it's looking fine, with almost no trend - see screenshot. It's chugging along happily with an 1800s timestep, taking 80min/yr on Broadwell (3.2KSU/yr) so I'll have a longer timeseries tomorrow.
![screen shot 2017-09-05 at tue 5-9 3 45pm](https://user-images.githubusercontent.com/31054815/30046891-4fe43b46-9251-11e7-9315-a67383ebfe38.png)

**Comment by nicjhan** [comment]
Thank you for the update @aekiss. I think we can close this issue now. Thank you to everyone who contributed to solving this! In summary we have fixed the following problems:

- sign of the incoming salt flux from CICE was incorrect. 
- in the 1 deg config different values were being used for ice reference salinity between MOM and CICE
- in MOM ocean_sbc.F90 for ACCESS runs when zero_net_water_coupler=.true. (wfimelt + wfiform) was being used instead of (salt_flux*reference_salinity) when calculating global PME. This means that precipitation falling on ice was not included in the zero net correction and was contributing to sea level rise. 
- the CICE coupling arrays were being sent before the CICE tilmestep was completely finished. For example pond water had not been removed from fresh water flux etc. See https://github.com/OceansAus/access-om2/issues/18
