### ISSUE TITLE
Ocean heat increasing

### ISSUE THREAD

**Issue by aekiss** [OceansAus/access-om2#35]
025deg_jra55_ryf_spinup7
      exe: matm_jra55_0609e5ad.exe
      exe: fms_ACCESS-OM_030fb1f2.x
      exe: cice_auscom_1440x1080_480p_fe730022.exe
Has no trend in salt or eta_t but total ocean heat is increasing (and potential energy decreasing) 
with a linear trend over 40 years with no sign of levelling off. Trends are a fairly large fraction of the  annual cycle. Might a net input of heat over the JRA55-RYF9091 annual cycle cause this? Or would we expect this to level off? @AndyHoggANU do you see this at 1 deg? I'll look at cumulative heat fluxes tomorrow to try to narrow down the culprit.

see /g/data3/hh5/tmp/cosima/access-om2-025/025deg_jra55_ryf_spinup7/output*/ocean/ocean_scalar.nc

<img width="659" alt="screen shot 2017-09-10 at sun 10-9 9 36pm" src="https://user-images.githubusercontent.com/31054815/30248763-a6d2ea00-9671-11e7-9810-350b15e1b3aa.png">

<img width="657" alt="screen shot 2017-09-10 at sun 10-9 9 52pm" src="https://user-images.githubusercontent.com/31054815/30248813-732e7628-9672-11e7-9f72-2bcf0472901c.png">

<img width="659" alt="screen shot 2017-09-10 at sun 10-9 9 42pm" src="https://user-images.githubusercontent.com/31054815/30248768-aea47690-9671-11e7-8f88-a85860ff8d90.png">

**Comment by StephenGriffies** [comment]
So long as the model diagnostics are showing that the heat entering the ocean = heat gained by the ocean, then there is no numerical error.  As we have worked hard to remove heat bugs, I suspect all is find numerically.  In that case,  what we are seeing, instead, is model drift.  

Consider a case where the area mean SST is systematically colder than the area mean "observed" SSTs used for developing the CORE atmospheric state. In that case, the bulk formula fluxes will pump more heat into the ocean (cold biased SST means more sensible heating and less longwave cooling). The added heat flux into the ocean will lead to an upward drift for the ocean heat content.  

If we run for roughly 1000 years, then the model should have reached a steady state by then. If we are not that patient (want to run shorter instead), then one must decide whether the model drift is sufficiently small as to "call it a day".  

There are many sources of model drift, such as uncertain subgrid scale settings.  We also should expect some model drift, since the initial state of the ocean is not a perfect match with obs.  Also, today's ocean does not correspond to an equilibrium state for today's surface fluxes.  Rather, today's ocean is the result of "integrating" for ~1000 years.  

So there a huge number of reasons that conspire to give us model drift. Our aim is to minimize the drift by doing things smart.  But we will never eliminate it completely.  Nor should we expect to do so even with a "perfect" model. Namely, we will never have full information about climate forcing or initial conditions from the distant past that is sufficient to generate a drift-free model.

**Comment by AndyHoggANU** [comment]
Hi @StephenGriffies, I agree with this statement. This latest spinup (spinup7 in the plot below) drifts much more slowly than the equivalent simulation using MOM-SIS at 0.25°, which is in principle good news (although we would like to dig deeper to find out where and how the drift is occurring).  

![index2](https://user-images.githubusercontent.com/26753100/30301938-1c2eceec-97a1-11e7-801a-91b041b08836.png)

**Comment by aekiss** [comment]
Thanks @StephenGriffies - yes, this is model drift (the MOM diagnostics show a beautifully closed ocean heat budget). I was wondering whether the 1990/1 repeat year forcing might be putting in an anomalous amount of heat.  total_net_sfc_heating is 2.42e+14 W (20 year average). This is about double the IPCC5AR observational estimate of 1.3e14 W we'd expect for "perfect" model, initial conditions, forcing, etc, neglecting any deep ocean changes (WG1AR5_ALL_FINAL.pdf sec B.2 gives observed change of 15-19e22 J in upper ocean heat over 40 yrs (1971-2010), ie 1.2-1.5e14 W). I'm not sure if that counts as "close enough" or whether we should revisit our forcing to try to reduce it. Expressed as a flux it is 0.67 W/m^2.

@AndyHoggANU - A summary of the components: Shortwave flux (58e15 W) is by far the largest positive contribution. Losses are dominated by latent heat (-34.9e15 W), followed by longwave radiation (-18.7e15 W) and a small loss by sensible heat (-3.5e15 W). There are a few other terms of even less significance. Individual flux time series appear reasonable, stabilising after ~20yr. The total (0.24e15 W) is a very small residual, so finding a cause for the drift is difficult.

**Comment by AndyHoggANU** [comment]
I think we should close this issue. Heat uptake is being monitored in many ways in our simulations. I don’t have permission to close issues, so can someone do it for me?

**Comment by aidanheerdegen** [comment]
I have also made you an owner @AndyHoggANU (oversight, should have done this already)
