### ISSUE TITLE
Use mushy thermodynamics in CICE to avoid negative salinity

### ISSUE THREAD

**Issue by aekiss** [OceansAus/access-om2#56]
With MOM-SIS 0.1deg, KDS75 & Russ's bathy we found that salinities could go negative, which @Hallberg-NOAA diagnosed as being due to ice formation in regions fresher than `ice_bulk_salin=0.005` in SIS:
https://arccss.slack.com/archives/C6WBMAS1K/p1507688360000037 

We dealt with this at the time by setting `ice_bulk_salin=0.0` as a stop-gap (and also filling in part of Yenesei Gulf) but Bob suggested mushy thermodynamics in CICE would be a good long-term solution.

Can anyone see a reason not to use mushy ice for ACCESS-OM2-01?

I'm not sure what needs to be changed in MOM/CICE/OASIS to make this work.

CICE changes would include setting `ktherm = 2` in cice_in.nml; I'm not sure what else.

With variable ice salinity, OASIS would need to couple the salt flux explicitly because MOM can't calculate it from melt. Is this already set up in namcouple? It currently includes
```
########## 
# Field 15 : salt flux   (no ref no for saltflux yet!)
##########
stflx_io salt_flx 454 400 1 i2o.nc EXPORTED
3600 2700 3600 2700 cict cict LAG=0 SEQ=+1
P 0 P 0
```

For MOM, presumably some changes are needed mom_oasis3_interface_nml (eg adding salt_flx to fields_in; increasing num_fields_in)? Are any changes needed in in auscom_ice_nml?

Presumably advecting variable salinity around will be extra work for CICE; I don't have a feel for whether that could upset load balancing.

**Comment by russfiedler** [comment]
@aekiss  No, the salt flux should be ok and is passed between components. CICE should be doing that correctly (I hope) provided there is sufficient salt in the top layer of the ocean. 

One problem is that mom tries to diagnose the amount of water removed by ice formation/melting when it tries to zero out the global water flux. If the ocean/ice reference salinities aren't the same then you get problems. You could just flat out require the global water flux be zero and ignore the sea ice  cycling back and forward. Alternatively, you could apply some iterative process that either scales the precipitation or adds an offset so that you get a long term zero waterflux.  This won't solve salinity going to low though.

I presume that the mushy ice physics needs to know the thickness of the top layer or, equivalently, the total amount of salt in the top layer or you still might be trying to remove salt that isn't there...

Applying stronger salinity forcing may work ok. There's also a switch in  mom_sponges_tracer.F90 to turn on very strong restoring of salt when it drops below a prescribed value. I guess this could be implemented in the surface restoring code instead.

**Comment by ofa001** [comment]
Hi @aekiss and @russfiedler The Met office had issues with low salinity in their model and they increased the salinities of their ice to 8 ppt to get round it.  We never ran with the mushy physics accept accidently when the wrong settings were left on in the namelist so I don't have experience with it, but it is widely used, its not set up to couple to the UM yet.

**Comment by aidanheerdegen** [comment]
FYI, people who aren't on the slack channel can't view that content. That may be a feature or a bug ...

**Comment by aekiss** [comment]
Yeah I know. I'm just trying to at least remind myself of what's been discussed where.

**Comment by aekiss** [comment]
Dave Bailey says "Salinity exchange between the sea ice and ocean is still fixed at 4 psu in CICE regardless of the thermodynamics."  (email 2017-11-29) so it looks like mushy thermodynamics will not avoid negative salinity.

**Comment by StephenGriffies** [comment]
That's a shame.  

I suggest clarifying this point also from Hallberg.  Perhaps mushy thermo in SIS2 allows for continuous salinity values, but not in CICE...?

**Comment by aekiss** [comment]
Closing this issue. 

Negative salinities were resolved by @russfiedler's commit https://github.com/mom-ocean/MOM5/commit/2d76b70ca66173f8dfcfdb0597c9b148ef4a7510

This sets the local ocean-ice salt flux to zero in regions where the seawater salinity is less than ocean_ice_salt_limit. Since we use zero_net_salt_restore = true, in these regions the sea ice salt is instead obtained from the global surface ocean at large. Over a sea ice formation and melt cycle this produces a small unphysical transport of salt from the global surface ocean to regions where such sea ice melts.

Sea ice formed in regions saltier than ocean_ice_salt_limit obtains its salt locally as usual.
