### ISSUE TITLE
matm compile error

### ISSUE THREAD

**Issue by PaulSpence** [OceansAus/access-om2#58]
Hi folks,

Following your beautiful instructions I have come across the following compiler error:

[pas561@raijin3 bin]$ cd $ACCESS_OM_DIR/src/matm
cd /short/v45/pas561/access-om2/src/matm
[pas561@raijin3 matm]$ make
gmake
build/build.sh core

...

mpif90 -c -r8 -i4 -O2 -align all -g -traceback -w -fpe0 -ftz -convert big_endian -assume byterecl -assume buffered_io -check noarg_temp_created  -I. -I/short/v45/pas561/access-om2/src/matm/source -I. -I/include -I/short/v45/pas561/access-om2/src/oasis3-mct//Linux/build/lib/psmile.MPI1 -I/short/v45/pas561/access-om2/src/oasis3-mct//Linux/build/lib/pio -I/short/v45/pas561/access-om2/src/oasis3-mct//Linux/build/lib/mct cpl_netcdf_setup.f90  
cpl_netcdf_setup.f90(7): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [NETCDF]
use netcdf
----^
cpl_netcdf_setup.f90(27): error #6404: This name does not have a type, and must have an explicit type.   [NF90_NOERR]
    if (status /= nf90_noerr) then ....

Andy Hogg doesn't get this error. We tried loading different types of netcdf modules.

Cheers
Paul

**Comment by rmholmes** [comment]
I have run into exactly the same problem trying to get access-om2 compiled using the install.sh

Since we're all using NCI, it'd be great to get some guidance on what libraries/modules we should be using. E.g. Include something like the following in install.sh:
`module purge
 module load netcdf/???
 ...
`
Nic gave me something like this for MOM6 recently.

Cheers,
Ryan

**Comment by PaulSpence** [comment]
try
module unload payu
module load payu/dev

**Comment by rmholmes** [comment]
Thanks Paul.

`[rmh561@raijin5 access-om2]$ module load payu/dev`
`payu(3):ERROR:105: Unable to locate a modulefile for 'payu/dev'`

Am I not in the right software group or project?

**Comment by PaulSpence** [comment]
or payu/0.8 should work also.

P

**Comment by aidanheerdegen** [comment]
I don't think `payu` should make a difference to your compilation. I've invited you to a slack channel @rmholmes which might be an easier place to resolve this

**Comment by PaulSpence** [comment]
yeah, good point. how did we solve this last week? 
P

**Comment by PaulSpence** [comment]
but you'll need to use payu/0.8 to run the model. Trying to remember how I solved the compiler error. There were a few hiccups in compilation ..

**Comment by rmholmes** [comment]
I haven't got a slack invitation as yet Aidan? What's the workspace?

**Comment by PaulSpence** [comment]
Oh yeah, now I remember. I just copied Andy's exe 👍 . Never got it to compile myself 👎

**Comment by nicjhan** [comment]
Has this problem seems to have mysteriously disappeared? @PaulSpence, @rmholmes did you figure out what the problem was? 

From slack:

Russ Fiedler [5:31 PM] 
environment variable NETCDF_ROOT wasn't being recognised by your Makefile. You can see there an include path `-I/include` in your compilation. It should be /apps/netcdf/4.4.1.1/include No  idea why it isn't making it there. Maybe a dodgy invisible character in the makefile?

rmholmes [5:52 PM] 
Strange, it seems to be working for me now. I am trying again completely afresh

**Comment by rmholmes** [comment]
@nicjhan no we never figured it out as it seemed to disappear by itself. I will let you know if it comes up again.
