### ISSUE TITLE
Remove use of intercommunicators so that profiling can be done with scorep

### ISSUE THREAD

**Issue by nichannah** [OceansAus/access-om2#89]
scorep cannot profile code which uses MPI intercommunicators. Remove the use of these and hard code global rank ids instead. 

This is for the purposes of profiling only.

**Comment by nicjhan** [comment]
I’ve pushed new branches to matm and cice called 89-scorep. they hard-code the ranks so that matm and ice can talk to each other. the most recent executables are here: /short/e14/nah599/access-om2/bin

also it’s necessary to make sure that your mpirun command looks like this:
mpirun --mca orte_base_help_aggregate 0 -wdir /short/e14/nah599/access-om2/work/1deg_jra55_ryf/atmosphere -np 1  /short/e14/nah599/access-om2/bin/matm_jra55_e227de2a.exe : -wdir /short/e14/nah599/access-om2/work/1deg_jra55_ryf/ice -np 24  /short/e14/nah599/access-om2/bin/cice_auscom_360x300_24p_4cf73a56.exe : -wdir /short/e14/nah599/access-om2/work/1deg_jra55_ryf/ocean -np 216  /short/e14/nah599/access-om2/bin/fms_ACCESS-OM_282c6f63.x

oh, that’s a bit hard to read. basically just matm first then cice. I did this by swapping the order of the models around in config.yaml
I’ve testted it with the 1 deg.

**Comment by russfiedler** [comment]
@nicjhan  Wouldn't it have been easir/cleaner to make an intracommunicator between CICE and MATM with `oasis_get_intracomm`? This connects the root processors of the two components. You don't need to hardwire anything.

**Comment by marshallward** [comment]
Thanks Nic, this appears to be working now.  Hopefully the Score-P developers will have a suggestion or fix for going back to the old version.
